name: Docker Build

on:
  push:
    branches:
      - master
      - main

  workflow_dispatch:

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: wine-quality-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify Docker Image
        run: |
          docker images
